{{ if or .Values.wso2.deployment.am.extraUserStores .Values.wso2.deployment.dependencies.ldap }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "am-pattern-1.resource.prefix" . }}-am-1-userstore
  namespace : {{ .Release.Namespace }}
  {{ if .Values.wso2.deployment.am.extraUserStores }}
data:
  {{- range $index, $content := .Values.wso2.deployment.am.extraUserStores }}
  {{ $index }}: |-
  {{ tpl $content $ | indent 4 }}
  {{- end }}

  {{ else if .Values.wso2.deployment.dependencies.ldap }}
stringData:
  {{ lower (.Values.agave.tenant.code | replace "." "_") }}.enc: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <UserStoreManager class="org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager">
      <Property name="ConnectionURL">ldap://{{ .Release.Name }}-openldap:{{ default .Values.openldap.port 389 }}</Property>
      <Property name="ConnectionName">cn=admin,dc=agaveplatform,dc=org</Property>
      <Property name="ConnectionPassword">{{ .Values.openldap.adminPassword }}</Property>
      <Property name="UserSearchBase">ou=People,ou=tenant{{ .Values.agave.tenant.code }},dc=agaveplatform,dc=org</Property>
      <Property name="UserEntryObjectClass">identityPerson</Property>
      <Property name="UserNameAttribute">uid</Property>
      <Property name="UserNameSearchFilter">(&amp;(objectClass=person)(uid=?))</Property>
      <Property name="UserNameListFilter">(objectClass=person)</Property>
      <Property name="UserDNPattern"/>
      <Property name="DisplayNameAttribute">uid</Property>
      <Property name="Disabled">false</Property>
      <Property name="ReadGroups">true</Property>
      <Property name="WriteGroups">true</Property>
      <Property name="GroupSearchBase">ou=Groups,ou=tenant{{ .Values.agave.tenant.code }},dc=agaveplatform,dc=org</Property>
      <Property name="GroupEntryObjectClass">groupOfNames</Property>
      <Property name="GroupNameAttribute">cn</Property>
      <Property name="GroupNameSearchFilter">(&amp;(objectClass=groupOfNames)(cn=?))</Property>
      <Property name="GroupNameListFilter">(objectClass=groupOfNames)</Property>
      <Property name="RoleDNPattern"/>
      <Property name="MembershipAttribute">member</Property>
      <Property name="MemberOfAttribute"/>
      <Property name="BackLinksEnabled">false</Property>
      <Property name="UserNameJavaRegEx">[a-zA-Z0-9._-|//]{3,30}$</Property>
      <Property name="UserNameJavaScriptRegEx">^[\S]{3,30}$</Property>
      <Property name="UsernameJavaRegExViolationErrorMsg">Username pattern policy violated.</Property>
      <Property name="PasswordJavaRegEx">^[\S]{5,30}$</Property>
      <Property name="PasswordJavaScriptRegEx">^[\S]{5,30}$</Property>
      <Property name="PasswordJavaRegExViolationErrorMsg">Password pattern policy violated.</Property>
      <Property name="RoleNameJavaRegEx">[a-zA-Z0-9._-|//]{3,30}$</Property>
      <Property name="RoleNameJavaScriptRegEx">^[\S]{3,30}$</Property>
      <Property name="LDAPInitialContextFactory">com.sun.jndi.ldap.LdapCtxFactory</Property>
      <Property name="BulkImportSupported">true</Property>
      <Property name="EmptyRolesAllowed">true</Property>
      <Property name="PasswordHashMethod">PLAIN_TEXT</Property>
      <Property name="MultiAttributeSeparator">,</Property>
      <Property name="MaxUserNameListLength">100</Property>
      <Property name="MaxRoleNameListLength">100</Property>
      <Property name="kdcEnabled">false</Property>
      <Property name="defaultRealmName">{{ upper (.Values.agave.tenant.code | replace "." "_") }}</Property>
      <Property name="UserRolesCacheEnabled">true</Property>
      <Property name="ConnectionPoolingEnabled">false</Property>
      <Property name="LDAPConnectionTimeout">5000</Property>
      <Property name="ReadTimeout">5000</Property>
      <Property name="RetryAttempts">0</Property>
      <Property name="CountRetrieverClass"/>
      <Property name="java.naming.ldap.attributes.binary"> </Property>
      <Property name="ClaimOperationsSupported">true</Property>
      <Property name="MembershipAttributeRange">0</Property>
      <Property name="UserCacheExpiryMilliseconds"/>
      <Property name="UserDNCacheEnabled">true</Property>
      <Property name="StartTLSEnabled">false</Property>
      <Property name="ConnectionRetryDelay">120000</Property>
      <Property name="SSLCertificateValidationEnabled">true</Property>
      <Property name="DomainName">{{ upper (.Values.agave.tenant.code | replace "." "_") }}</Property>
      <Property name="Description">Hosted OpenLDAP user store deployed and managed by the Agave Platform</Property>
    </UserStoreManager>
  {{ end }}
{{ end }}