apiVersion: v1
kind: Service
metadata:
  name: {{ template "am-mysql.resource.prefix" . }}-rdbms-service-mysql
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    deployment: {{ template "am-mysql.resource.prefix" . }}-mysql
    product: api-manager
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      protocol: TCP
