apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "am-mysql.resource.prefix" . }}-mysql-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: {{ template "am-mysql.resource.prefix" . }}-mysql
      product: api-manager
  template:
    metadata:
      labels:
        deployment: {{ template "am-mysql.resource.prefix" . }}-mysql
        product: api-manager
    spec:
      containers:
        - name: {{ template "am-mysql.resource.prefix" . }}-mysql
          image: mysql:5.7
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            initialDelaySeconds: 60
            periodSeconds: 10
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 999
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: {{ template "am-mysql.resource.prefix" . }}-mysql-dbscripts
              mountPath: /docker-entrypoint-initdb.d
          args: ["--max-connections", "10000"]
      volumes:
        - name: {{ template "am-mysql.resource.prefix" . }}-mysql-dbscripts
          configMap:
            name: {{ template "am-mysql.resource.prefix" . }}-mysql-dbscripts
      serviceAccountName: {{ .Values.kubernetes.serviceAccount }}
